services:
  # Frontend development service
  frontend-dev:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=http://localhost:3001
      - CHOKIDAR_USEPOLLING=true
    networks:
      - app-network

  # Backend development service
  backend-dev:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=3001
      - FRONTEND_URL=http://localhost:3000
      - FIRESTORE_EMULATOR_HOST=firestore-emulator:8080
      - FIRESTORE_EMULATOR_PROJECT_ID=demo-project
    depends_on:
      - firestore-emulator
    networks:
      - app-network

  # Firestore emulator
  firestore-emulator:
    image: gcr.io/google.com/cloudsdktool/cloud-sdk:emulators
    command: gcloud beta emulators firestore start --host-port=0.0.0.0:8080 --project=demo-project
    ports:
      - "8080:8080"
    environment:
      - FIRESTORE_EMULATOR_HOST=0.0.0.0:8080
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
